### ISSUE TITLE
when i run bash run.sh --stage 4 --stop-stage 4 ,got error:

### ISSUE THREAD

**Issue by dayu1979** [mobvoi/wenet#154]
Traceback (most recent call last):
  File "wenet/bin/train.py", line 209, in <module>
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/media/dayu/D/nlp/wenet/examples/aishell/s0/wenet/utils/executor.py", line 35, in train
    loss, loss_att, loss_ctc = model(feats, feats_lengths, target,
  File "/home/dayu/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/dayu/D/nlp/wenet/examples/aishell/s0/wenet/transformer/asr_model.py", line 89, in forward
    encoder_out, encoder_mask = self.encoder(speech, speech_lengths)
  File "/home/dayu/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/dayu/D/nlp/wenet/examples/aishell/s0/wenet/transformer/encoder.py", line 133, in forward
    masks = ~make_pad_mask(xs_lens).unsqueeze(1)  # (B, 1, L)
  File "/media/dayu/D/nlp/wenet/examples/aishell/s0/wenet/utils/mask.py", line 140, in make_pad_mask
    max_len = int(lengths.max().item())
RuntimeError: CUDA error: no kernel image is available for execution on the device

my evn is ubuntu20.04,cuda11.1 torch17.1

**Comment by placebokkk** [comment]
please follow the readme to setup your env.

install miniconda

conda create -n wenet python=3.8
conda activate wenet
pip install -r requirements.txt
conda install pytorch==1.6.0 cudatoolkit=10.1 torchaudio -c pytorch
